DROP TABLE IF EXISTS `#__joomgallery`;
DROP TABLE IF EXISTS `#__joomgallery_categories`;
DROP TABLE IF EXISTS `#__joomgallery_collections`;
DROP TABLE IF EXISTS `#__joomgallery_collections_ref`;
DROP TABLE IF EXISTS `#__joomgallery_comments`;
DROP TABLE IF EXISTS `#__joomgallery_configs`;
DROP TABLE IF EXISTS `#__joomgallery_faulties`;
DROP TABLE IF EXISTS `#__joomgallery_fields`;
DROP TABLE IF EXISTS `#__joomgallery_img_types`;
DROP TABLE IF EXISTS `#__joomgallery_migration`;
DROP TABLE IF EXISTS `#__joomgallery_tags`;
DROP TABLE IF EXISTS `#__joomgallery_tags_ref`;
DROP TABLE IF EXISTS `#__joomgallery_tasks`;
DROP TABLE IF EXISTS `#__joomgallery_users`;
DROP TABLE IF EXISTS `#__joomgallery_votes`;
DROP TABLE IF EXISTS `#__joomgallery_task_items`;

DELETE FROM `#__assets` WHERE (name LIKE 'com_joomgallery%');
DELETE FROM `#__content_types` WHERE (type_alias LIKE 'com_joomgallery%');
DELETE FROM `#__mail_templates` WHERE (extension LIKE 'com_joomgallery%');
DELETE `#__fields_values` FROM `#__fields_values` INNER JOIN `#__fields` ON `#__fields`.`id` = `#__fields_values`.`field_id` WHERE (`#__fields`.`context` LIKE 'com_joomgallery%');
DELETE FROM `#__fields_groups` WHERE (context LIKE 'com_joomgallery%');
DELETE FROM `#__fields` WHERE (context LIKE 'com_joomgallery%');
DELETE FROM `#__scheduler_tasks` WHERE (type LIKE 'joomgallery%');
DELETE `#__finder_links` FROM `#__finder_links` INNER JOIN `#__finder_types` ON `#__finder_types`.`id` = `#__finder_links`.`type_id` WHERE (`#__finder_types`.`title` LIKE 'Image (JoomGallery)');
DELETE `#__finder_types` FROM `#__finder_types` WHERE (`#__finder_types`.`title` LIKE 'Image (JoomGallery)');
