name: CI JoomGallery

on:
  pull_request:
    branches:
      - master
      - 'v*'

jobs:
  prepare:
    name: PR preparations
    if: github.base_ref == 'master' || startsWith(github.base_ref, 'v')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      - name: Clean up unnecessary files
        run: |
          rm -rf crowdin.yml composer.json composer.lock docs tests .github .editorconfig

      - name: Cleanup pel directory
        run: |
          PEL_DIR="administrator/com_joomgallery/vendor/fileeye/pel"
          find "$PEL_DIR" -mindepth 1 -maxdepth 1 ! -name 'src' ! -name 'autoload.php' ! -name 'composer.json' -exec rm -rf {} +

      - name: Sanitize PR title for filename
        id: pr
        run: |
          SAFE_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr -cd '[:alnum:]._-')
          echo "SAFE_TITLE=${SAFE_TITLE}" >> $GITHUB_OUTPUT

      - name: Upload artifact (GitHub will zip it)
        uses: actions/upload-artifact@v4
        with:
          name: JoomGallery-${{ steps.pr.outputs.SAFE_TITLE }}
          path: .
          retention-days: 60
  
  code-style-php:
    name: Check PHP code style
    runs-on: ubuntu-latest
    needs: [prepare]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      # Cache composer downloads + vendor to speed up installs
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            administrator/com_joomgallery/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Install WITH dev so cs tools are available
      - name: Install dependencies (with dev)
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

      - name: Run PHP-CS-Fixer
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
        run: ./administrator/com_joomgallery/vendor/bin/php-cs-fixer fix -vvv --dry-run --diff

      - name: Run PHPCS
        run: ./administrator/com_joomgallery/vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .

  static-analysis:
    name: Static PHP code analysis
    runs-on: ubuntu-latest
    needs: [code-style-php]

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      # Cache composer downloads + vendor to speed up installs
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache/files
            administrator/com_joomgallery/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Install WITH dev so cs tools are available
      - name: Install dependencies (with dev)
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

      - name: Run PHPstan
        run:  ./administrator/com_joomgallery/vendor/bin/phpstan --error-format=github
